server:
  port: 9201
spring:
  application:
    name: yang-service-goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    config:
      name: application
      profile: test
      label: master
      uri: http://127.0.0.1:9401
eureka:
  client: 
    service-url:  
      defaultZone: http://127.0.0.1:9200/eureka
    register-with-eureka: true  
    fetch-registry: true        
  instance:
    hostname: localhost            
    prefer-ip-address: true   
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
